# Generated by Django 3.2.7 on 2021-11-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0002_auto_20211113_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
